export const UPDATE_LAT_LONG = 'UPDATE_LAT_LONG';
export const UPDATE_WEATHERDESC_TEMP = 'UPDATE_WEATHERDESC_TEMP';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';