export const UPDATE_LAT_LONG = 'UPDATE_LAT_LONG';
export const UPDATE_WEATHERDESC_TEMP = 'UPDATE_WEATHERDESC_TEMP';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';
export const GET_FIVE_DAY_WEATHER = 'GET_FIVE_DAY_WEATHER';
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';